---
- name: Deploy Healthcare App with Docker
  hosts: localhost
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Log in to Docker daemon (if needed)
      command: docker ps
      register: docker_status
      ignore_errors: yes

    - name: Build Docker image
      command: docker build -t healthcare-app:latest ./app
      args:
        chdir: /var/jenkins_home/workspace/healthcare-pipeline

    - name: Stop old container if running
      command: docker stop healthcare-app
      ignore_errors: yes

    - name: Remove old container if exists
      command: docker rm healthcare-app
      ignore_errors: yes

    - name: Run new Healthcare container
      command: docker run -d --name healthcare-app -p 5000:5000 healthcare-app:latest
